openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: Generated API documentation
paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: Successful response
